<?php
$js = array();

$js[] = "/public/jquery/jquery-2.2.2.min.js";
$js[] = "/public/ajax/ajax.js";
$js[] = "/modulos/base/web/js/ajax.common.js";

if (is_array($MyFrankyMonster->MyAjaxFile())) {
    if (count($MyFrankyMonster->MyAjaxFile()) > 0) {
        foreach ($MyFrankyMonster->MyAjaxFile() as $ajax) {
            $ajax = explode('/',$ajax);
            $js[]  = "/modulos/".$ajax[0]."/web/js/" . $ajax[1];
        }
    }
}

$FILE = new \Franky\Filesystem\File();
if (is_array($MyFrankyMonster->MyJQueyfile())) {
    if (count($MyFrankyMonster->MyJQueyfile()) > 0) {
        foreach ($MyFrankyMonster->MyJQueyfile() as $jquery) {

            $path = PROJECT_DIR."/public/jquery/$jquery/js/";
            $js_jquery = $FILE->getFiles($path);

            if(count($js_jquery) > 0)
            {
                foreach($js_jquery as $_js_jquery)
                {


                        $js[] = "/public/jquery/$jquery/js/".$_js_jquery;

                }
            }
        }
    }
}

$js[] = "/public/js/funciones.js";
$js[] = "/modulos/base/web/js/front.js";
$js[] = "/modulos/base/web/js/admin.js";
$js[] = "/public/js/menu.js";
$js[] = "/public/js/blocks.js";
$js[] = "/public/js/franky.mobile.js";

if (is_array($MyFrankyMonster->MyJSFile())) {
    if (count($MyFrankyMonster->MyJSFile()) > 0) {
        foreach ($MyFrankyMonster->MyJSFile() as $_js) {
            if(!empty($js))
            {
                $js[] ='/modulos/'.$MyFrankyMonster->MyModulo().'/web/js/' . $_js ;

            }
        }
    }
}

if (is_array($MyMetatag->getJs(false))) {
    if (count($MyMetatag->getJs(false)) > 0) {
        foreach ($MyMetatag->getJs(false) as $_js) {
            if(!empty($js))
            {
                $js[] = $_js ;

            }
        }
    }
}
$render_js = getJSEmbebed($render_phtml);

$js = getJqueryUIjs($js,$render_js);

?>
    <script >
     <!--
        var idioma_sitio = '<?php echo $lang_root; ?>'

        function isMobile(){ return <?php echo ($Mobile_detect->isMobile() ? 'true' : 'false'); ?>; };

        <?php
        if(file_exists(PROJECT_DIR."/modulos/".$MyConfigure->getPathSite()."/configure/blocks.php"))
        {
            $blocks = include(PROJECT_DIR."/modulos/".$MyConfigure->getPathSite()."/configure/blocks.php");
            echo 'var blocks_html = '.$blocks.';';
        }
        else{
            echo 'var blocks_html ={};';
        }   
        ?>
     // -->
    </script>
<?php

foreach($js as $_file_js)
{
    ?>
    <script src='<?php echo $_file_js; ?>'  ></script>
    <?php
}
?>
<script >
    <!--
    <?php echo $render_js; ?>
    //-->
</script>
