<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin">Dispositivos</h1>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
                    <form name="buscarGrid" action="" method="get" id="paginar">                
                        <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
                    </form>
                </div>
            </div>
        <div  class="w-xxxx-12 cont_gral_admin cont_devices">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script >

$(window).load(function(){
    var isGridMobile = ($(window).width() <= 767 ? true : false);

    $("#jqGrid").GridAdmin({
        search : true,
        entity : 'devicesa',
        redirectOnSelectRow:false,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '',
        pathData : window.location.pathname,
        error : "<?=_calificaciones("No hay registros")?>",
        deleteFunction : "",
        colModel: [
            { label: '<?=_('ID')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('Fecha')?>', name: 'access_last', width: 150,
                
                searchoptions: {
                    dataInit: function (element) {
                        $(element).datepicker({
                            id: 'orderDate_datePicker',
                            dateFormat:"yy-mm-dd",
                            maxDate: "+0D",
                            showOn: 'focus'
                        });
                    },
                    sopt: ["ge","le","eq"]
                }
            },
            { label: '<?=_('Tipo')?>', name: 'type', width: 100 },
            { label: '<?=_('OS')?>', name: 'os',  width: 100},
            { label: '<?=_('IP')?>', name: 'ip',  width: 250 },
            { label: '<?=_('User Agent')?>', name: 'user_agent', width: 250, hidden:true, },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 250, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones
            }
        ],
        subGrid: true,
        subGridRowExpanded: showChildGrid,
        callbackFuncion:'deleteDevices',
        width:900
    });
 });

 function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId; // Obtiene el ID único de la fila actual
     
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton1 = '<a class="_btn_adm_eliminar " data-id="'+id+'" href="#desactivar"><span class="icon icon-r-eliminar"> </span></a> ';
    var boton2 = '<a class="btn_adm_eliminar_switch_device" data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';
    
    return boton1 + boton2;                       
}


function deleteDevices() {
    $.fn.buttonDelete('a.btn_adm_eliminar_switch_device')
    
    $(".btn_adm_eliminar_switch_device").click(function(event){
        event.preventDefault();
        var nuevo_estado = ($(this).attr("href").replace("#","") == "activar" ? 1 : 0);
        EliminarDevice('BloquearDispositivo',$(this).attr("data-id"),nuevo_estado,'',"EliminarRegistroPanel")

        
    });

    $("._btn_adm_eliminar").click(function(event){
        event.preventDefault();
        EliminarDevice('EliminarDispositivo',$(this).attr("data-id"),0,'¿Realmente quieres eliminar el dispositivo?',"EliminarRegistorPanelRemove")

    });
}

function showChildGrid(parentRowID, parentRowKey) {
    var childGridID = parentRowID + "_table";
    var childGridPagerID = parentRowID + "_pager";

        var agent  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_user_agent"]').text();
      
        $('#' + parentRowID).append('<p>User Agent: '+agent+'</p>');
       
    
}
</script>
