
<div class="content">

    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?> </div>

        <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin"><?=_('Email Templates')?></h1>
        
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
                <form name="buscarGrid" action="" method="get" id="paginar">                
                        <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
                </form>
               
                  <a href="<?php echo $MyRequest->url(FRM_EMAIL_TEMPLATE); ?>" class="_btn_new">Nuevo</a>
                
            </div>
        </div>

        <div  class="w-xxxx-12 cont_gral_admin">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script >
$(window).load(function(){
    var isGridMobile = ($(window).width() <= 767 ? true : false);
    $("#jqGrid").GridAdmin({
        search : true,
        entity : 'users',
        redirectOnSelectRow:true,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '<?=$MyRequest->link(FRM_EMAIL_TEMPLATE)?>',
        pathData : '<?=$MyRequest->url(LISTA_EMAIL_TEMPLATE)?>',
        error : "<?=_('No hay templates registrados')?>",
        deleteFunction : "EliminarTemplate",
        colModel: [
            { label: '<?=_('ID BACK')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('Callback')?>', name: 'callback',  hidden:true, width: 50 },
            { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
            { label: '<?=_('ID')?>', name: '_id',hidden:isGridMobile, width: 100 },
            { label: '<?=_('Nombre')?>', name: 'nombre', width: 250 },
            { label: '<?=_('Asunto')?>', name: 'Asunto', width: 250 },
            { label: '<?=_('HTML')?>', name: 'html', hidden:true, width: 250 },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 200, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones 
            }
        ],
        subGrid: true,
        subGridRowExpanded: showChildGrid,
        width:840
    });
});
function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId;
     
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton1 = '<a href="<?=$MyRequest->link(FRM_EMAIL_TEMPLATE)?>?id=' + id + '&callback='+rowObject.callback+'" class="btn_adm_editar"><span class="icon icon-editar"> </span></a> ';
    var boton2 = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';

    return boton1 + boton2;
}
function showChildGrid(parentRowID, parentRowKey) {
    var childGridID = parentRowID + "_table";
    var childGridPagerID = parentRowID + "_pager";
    var html  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_html"]').html();
    
    if($(window).width() <= 767) {
      
        var id  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="__id"]').text();
      
        $('#' + parentRowID).append('<p>ID: '+id+'</p>');
       
    }

    $('#' + parentRowID).append('<p>'+html+'</p>');

}
</script>
