<div class="width_100">
<?php echo render("registro/_form.user.phtml"); ?>
</div>
<script type="text/javascript">
window.captcha = {}
window.captcha.enabled = <?=getCoreConfig('base/user/captcha')?>;
window.captcha.msg = "<?=$MyMessageAlert->Message("recaptcha")?>";
</script>
<script>
$( "#users" ).validate({
rules: {
    email: {
        required: true,
        email: true,
        remote: {
            url: "/registro/email.php",
            type: "post",
            data: {
                email: function() {
                    return $( "input[name=email]" ).val();
                }
            }
        }
    },
    nombre: {
            required: true,
            'name-validation': true
    },
    fecha_nacimiento: {
            required: true,
    },
    contrasena: {
            required: true,
            minlength: <?=getCoreConfig('base/user/passwordlength')?>
    },
    contrasena1: {
            required: true,
            minlength: <?=getCoreConfig('base/user/passwordlength')?>,
            equalTo: "#contrasena"
    },
    acepto: {
            required: true
    }
},
messages: {
    nombre: {
              required: "Escribe tu nombre completo",
              'name-validation': 'El campo nombre contiene caracteres no permitidos'
              },
    fecha_nacimiento: {
        required: "Favor de seleccionar tu fecha de nacimiento",
    },
    contrasena: {
            required: "Escribe tu contrase&ntilde;a",
            rangelength: jQuery.validator.format("Tu contrase&ntilde;a debe tener mínimo {0} caracteres")
    },
    contrasena1: {
            required: "Repite tu contrase&ntilde;a",
            minlength: jQuery.validator.format("Tu contrase&ntilde;a debe tener mínimo {0} caracteres"),
            equalTo: "Tu contrase&ntilde;a no coincide"
    },
    email: {
            required: "Escribe tu direcci&oacute;n de correo electr&oacute;nico",
            remote: jQuery.validator.format("La direccion {0} ya esta en uso")
    },
     acepto: {
            required: "Debes aceptar las condiciones y terminos del servicio"
    }
},submitHandler: function(form)
                    {
                        if (window.captcha.enabled == 1) {
                            $('#recaptcha-error').hide().html('');
                            var response = grecaptcha.getResponse();
                            if(response.length == 0) 
                            { 
                                $('#recaptcha-error').html(window.captcha.msg).show();
                                return false;
                            }
                        }
                        $("form[name=users]").find("input[type=submit]").attr('disabled',true);
                        return true;

                    }
});
</script>
