<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12">
        <div class="content_form">
            <h1><?php echo $title_form; ?></h1>
            <div class="w-xxxx-5">
                <p>Aquí podrás editar la información de tu perfil.</p>
                <p>Recuerda, es importante que tu perfil esté completo.</p>
                <?php echo $adminForm->openTag(); ?>
                <?php echo $adminForm->get('id'); ?>
                <?php echo $adminForm->get('token_xsrf'); ?>
                    <?php echo $adminForm->get('callback'); ?>
                    <?php echo $adminForm->getRow('nombre'); ?>
                    <?php echo $adminForm->getRow('email'); ?>
                    <?php echo $adminForm->getRow('telefono'); ?>
                    <?php 
                    
                    if($MyAccessList->MeDasChancePasar("administrar_otros_usuarios")):
                      
                        echo $adminForm->getRow('role');
                        endif;
                    ?>
                    <?=(getCoreConfig("base/user/showgender") == 1 ? $adminForm->getRow('sexo') : "")?>
                    <?php echo $adminForm->getRow('fecha_nacimiento'); ?>
                    <div class="_tag_center">
                      <?php echo $adminForm->getRow('guardar'); ?>
                    </div>
                <?php echo $adminForm->endTag(); ?>
           </div>
       </div>
    </div>
</div>


<script >


$( "#users" ).validate({
rules: {
    email: {
        required: true,
        email: true,
        remote: {
            url: "/registro/email.php",
            type: "post",
            data: {
                email: function() {
                    return $( "input[name=email]" ).val();
                },
                id: function() {
                    return $( "input[name=id]" ).val();
                }
            }
        }
    },
    nombre: {
            required: true,
            'name-validation':true
    }

},
messages: {
  nombre: {
            required: "Escribe tu nombre completo",
            'name-validation': 'El campo nombre contiene caracteres no permitidos'
            },
    email: {
            required: "Escribe tu direcci&oacute;n de correo electr&oacute;nico",
            remote: jQuery.validator.format("La direcci&oacute;n de correo electr&oacute;nico ya esta en uso")
    }
}
});

</script>
