<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
        <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin">Usuarios</h1>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
            <form name="buscarGrid" action="" method="get" id="paginar">                
                <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
            </form>
            <a href="<?php echo $MyRequest->url(FRM_OPERADORES); ?>" class="_btn_new">Nuevo</a>
            </div>
            </div>
            <div  class="w-xxxx-12 cont_gral_admin cont_usuarios_reg">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
            </div>
           
    </div>
</div>
<script type="text/javascript">
    var administrar_otra_contrasena = <?=$MyAccessList->MeDasChancePasar("administrar_otra_contrasena")?>;
</script>
<script>
$(window).load(function(){
    var isGridMobile = ($(window).width() <= 767 ? true : false);

    var  userType = <?= json_encode(getRoles())?>;
     userType = ":Todos;"+ Object.entries(userType)
    .map(([id, nombre]) => `${id}:${nombre}`)
    .join(';');


    $("#jqGrid").GridAdmin({
        search : true,
        entity : 'users',
        redirectOnSelectRow:true,
        gridPager : "#jqGridPager",
        btnSearch: "#btsSearchGridAdmin",
        redirectPath : '<?=$MyRequest->link(FRM_OPERADORES)?>',
        pathData : '<?=$MyRequest->url(LISTA_OPERADORES)?>',
        error : "<?=_('No hay usuarios registrados')?>",
        deleteFunction : "EliminarUser",
        colModel: [
            { label: '<?=_('ID')?>', name: 'id', key:true, hidden:true, width: 50 },
            { label: '<?=_('Callback')?>', name: 'callback',  hidden:true, width: 50 },
            { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
            { label: '<?=_('Fecha registro')?>', name: 'fecha', width: 200, hidden:isGridMobile, 
                
                searchoptions: {
                    dataInit: function (element) {
                        $(element).datepicker({
                            id: 'orderDate_datePicker',
                            dateFormat:"yy-mm-dd",
                            maxDate: "+0D",
                            showOn: 'focus'
                        });
                    },
                    sopt: ["ge","le","eq"]
                }
             },
            { label: '<?=_('Email')?>', name: 'email',  width: 250 },
            { label: '<?=_('Nombre')?>', name: 'nombre', hidden:isGridMobile,  width: 250 },
            { label: '<?=_('Tipo de usuario')?>', name: 'role',   width: 250, stype: 'select',
                searchoptions: { value: userType}
             },
            { label:'<?=_('Tel&eacute;fono')?>', name: 'telefono', hidden:isGridMobile,  width: 250 },
            { 
            name: 'acciones', 
            index: 'acciones', 
            width: 200, 
            align: 'center', 
            sortable: false, 
            search: false,
            formatter: creadorDeBotones // Vincula la función que creamos en el paso 2
            }
        ],
        subGrid: isGridMobile,
        subGridRowExpanded: showChildGrid
    });
 });

 function creadorDeBotones(cellvalue, options, rowObject) {
    
    var id = options.rowId; // Obtiene el ID único de la fila actual
     
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton1 = '<a href="<?=$MyRequest->link(FRM_OPERADORES)?>?id=' + id + '&callback='+rowObject.callback+'" class="btn_adm_editar"><span class="icon icon-editar"> </span></a> ';
    if(administrar_otra_contrasena == 1) {
        var boton2 = '<a href="<?=$MyRequest->link(FRM_PASS_OPERADORES)?>?id=' + id + '&callback='+rowObject.callback+'" class="btn_adm_editar_pass"><span class="icon icon-d-contrasena"> </span></a> ';
    } else {
        var boton2 = '';
    }
    var boton3 = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';

    return boton1 + boton2 + boton3;
}

function showChildGrid(parentRowID, parentRowKey) {

    var childGridID = parentRowID + "_table";
    var childGridPagerID = parentRowID + "_pager";
    var comentario  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_comentario"]').text();
    if($(window).width() <= 767) {
        var fecha  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_fecha"]').text();
        var nombre  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_nombre"]').text();
        var telefono  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_telefono"]').text();
      
        $('#' + parentRowID).append('<p>Fecha: '+fecha+'</p>');
        $('#' + parentRowID).append('<p>Nombre: '+nombre+'</p>');
        $('#' + parentRowID).append('<p>Tel&eacute;fono: '+telefono+'</p>');
    }
}
</script>

