<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin">Contacto</h1>
        <div class="w-xxxx-12 cont_header_panel">
             <div class="_wrapp_form_serch">
                <form name="buscarGrid" action="" method="get" id="paginar">                
                        <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
                </form>
                <a href="/admin/contacto/excel.php" target="_blank" class="_btn_new">Exportar</a>

            </div>
        </div>
        <div  class="w-xxxx-12 cont_gral_admin cont_contactos">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script >
$(window).load(function(){
var isGridMobile = ($(window).width() <= 767 ? true : false);

$("#jqGrid").GridAdmin({
    search : true,
    entity : 'mailing',
    redirectOnSelectRow:false,
    gridPager : "#jqGridPager",
    btnSearch: "#btsSearchGridAdmin",
    redirectPath : '',
    pathData : '<?=$MyRequest->url(CONTACTOS_LIST)?>',
    error : "<?=_('No hay emails registrados')?>",
    deleteFunction : "EliminarComentario",
    colModel: [
        { label: '<?=_('ID')?>', name: 'id', key:true,  width: 100 },
        { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
        { label: '<?=_('Fecha')?>', name: 'fecha',  width: 180,
            
            searchoptions: {
                dataInit: function (element) {
                    $(element).datepicker({
                        id: 'orderDate_datePicker',
                        dateFormat:"yy-mm-dd",
                        maxDate: "+0D",
                        showOn: 'focus'
                    });
                },
                sopt: ["ge","le","eq"]
            }
        },
        { label: '<?=_('Nombre')?>', name: 'nombre',hidden:isGridMobile,  width: 250 },
        { label: '<?=_('Tel&eacute;fono')?>', name: 'telefono',hidden:isGridMobile,  width: 250 },
        { label: '<?=_('Asunto')?>', name: 'asunto',  width: 250 },
        { label: '<?=_('Email')?>', name: 'email', hidden:isGridMobile, width: 250 },
        { label: '<?=_('Comentario')?>', name: 'comentario', hidden:true, width: 250 },
        { 
        name: 'acciones', 
        index: 'acciones', 
        width: 180, 
        align: 'center', 
        sortable: false, 
        search: false,
        formatter: creadorDeBotones,
        }
    ],
    subGrid: true,
    subGridRowExpanded: showChildGrid
});
});

function creadorDeBotones(cellvalue, options, rowObject) {

    var id = options.rowId;
    
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';

    return boton;
}

function showChildGrid(parentRowID, parentRowKey) {
    var childGridID = parentRowID + "_table";
    var childGridPagerID = parentRowID + "_pager";
    var comentario  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_comentario"]').text();
    if($(window).width() <= 767) {
        var fecha  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_fecha"]').text();
        var nombre  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_nombre"]').text();
        var email  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_email"]').text();
        var telefono  = $(this).find('#' + parentRowKey + ' td[aria-describedby$="_telefono"]').text();
      
        $('#' + parentRowID).append('<p>Fecha: '+fecha+'</p>');
        $('#' + parentRowID).append('<p>Nombre: '+nombre+'</p>');
        $('#' + parentRowID).append('<p>E-mail: '+email+'</p>');
        $('#' + parentRowID).append('<p>Tel&eacute;fono: '+telefono+'</p>');
    }
    $('#' + parentRowID).append('<p>'+comentario+'</p>');
}
</script>
