<div class="content">
    <div class="w-xxxx-12"><?php echo breadcrumbs(); ?></div>
    <div class="w-xxxx-12 cont_global_admin">
        <h1 class="titulo_seccion_admin">Newsletter</h1>
        <p>En esta sección podrás revisar los usuarios inscritos al Newsletter</p>
        <div class="w-xxxx-12 cont_header_panel">
            <div class="_wrapp_form_serch">
            <form name="buscarGrid" action="" method="get" id="paginar">                
                    <div class="form-group form_buscar"><input type="submit" name="buscar" class="_btn _primary" id="btsSearchGridAdmin" value="Buscar"></div>
            </form>
            <a href="/admin/mailing/excel.php" target="_blank" class="_btn_new">Exportar</a>
            </div>
        </div>
        <div  class="w-xxxx-12 cont_gral_admin cont_mailing">
            <table id="jqGrid"></table>
            <div id="jqGridPager"></div>
        </div>
    </div>
</div>

<script >
$(window).load(function(){

$("#jqGrid").GridAdmin({
    search : true,
    entity : 'mailing',
    redirectOnSelectRow:false,
    gridPager : "#jqGridPager",
    btnSearch: "#btsSearchGridAdmin",
    redirectPath : '',
    pathData : '<?=$MyRequest->url(MAILING)?>',
    error : "<?=_('No hay emails registrados')?>",
    deleteFunction : "EliminarEmailNews",
    colModel: [
        { label: '<?=_('ID')?>', name: 'id', key:true,  width: 100 },
        { label: '<?=_('Status')?>', name: 'status',  hidden:true, width: 50 },
        { label: '<?=_('Fecha')?>', name: 'fecha', width: 200,
            
            searchoptions: {
                dataInit: function (element) {
                    $(element).datepicker({
                        id: 'orderDate_datePicker',
                        dateFormat:"yy-mm-dd",
                        maxDate: "+0D",
                        showOn: 'focus'
                    });
                },
                sopt: ["ge","le","eq"]
            }
         },
        { label: '<?=_('Email')?>', name: 'email',  width: 250 },
        { 
        name: 'acciones', 
        index: 'acciones', 
        width: 200, 
        align: 'center', 
        sortable: false, 
        search: false,
        formatter: creadorDeBotones // Vincula la función que creamos en el paso 2
        }
    ],
    width:750
});
});

function creadorDeBotones(cellvalue, options, rowObject) {

    var id = options.rowId;
    
    var icon_delete = (rowObject.status  == "activar" ? 'icon-c-encender' : 'icon-r-eliminar');
    var boton = '<a class="btn_adm_eliminar " data-id="'+id+'" href="#'+rowObject.status+'"><span class="icon '+icon_delete+'"> </span></a>';

    return boton;
}
</script>
