<?php
return array
(
    "sitemap.xml" => PROJECT_DIR."/modulos/base/controller/sitemap.php",
    "lang.php" => PROJECT_DIR."/modulos/base/controller/lang.php",
    "login.php" => PROJECT_DIR."/modulos/base/controller/login.php",
    "admin/login.php" => PROJECT_DIR."/modulos/base/controller/admin/login.php",
    "logout.php" => PROJECT_DIR."/modulos/base/controller/logout.php",
    "forgot.php" => PROJECT_DIR."/modulos/base/controller/forgot.php",
    "admin/forgot.php" => PROJECT_DIR."/modulos/base/controller/admin/forgot.php",
    "contacto.submit.php" => PROJECT_DIR."/modulos/base/controller/contacto.submit.php",
    "registro/submit.users.php" => PROJECT_DIR."/modulos/base/controller/registro/submit.users.php",
    "registro/setVerificacion.php" => PROJECT_DIR."/modulos/base/controller/registro/setVerificacion.php",
    "registro/delete.profile.php" => PROJECT_DIR."/modulos/base/controller/registro/delete.profile.php",
    "registro/alias.php" => PROJECT_DIR."/modulos/base/controller/registro/alias.php",
    "registro/email.php" => PROJECT_DIR."/modulos/base/controller/registro/email.php",
    "mfm.php" => PROJECT_DIR."/modulos/base/controller/mfm.php",
    "mi-cuenta/users/submit.avatar.php" => PROJECT_DIR."/modulos/base/controller/mi-cuenta/users/submit.avatar.php",
    "mi-cuenta/users/chose.avatar.php" => PROJECT_DIR."/modulos/base/controller/mi-cuenta/users/chose.avatar.php",
    "mi-cuenta/users/submit.users.php" => PROJECT_DIR."/modulos/base/controller/mi-cuenta/users/submit.users.php",
    "mi-cuenta/users/submit.pass.php" => PROJECT_DIR."/modulos/base/controller/mi-cuenta/users/submit.pass.php",
    "admin/users/submit.users.php" => PROJECT_DIR."/modulos/base/controller/admin/users/submit.users.php",
    "admin/users/submit.pass.php" => PROJECT_DIR."/modulos/base/controller/admin/users/submit.pass.php",
    "admin/cms/submit.php"  => PROJECT_DIR."/modulos/base/controller/admin/cms/submit.php",
    "admin/template_email/submit.php" => PROJECT_DIR."/modulos/base/controller/admin/template_email/submit.php",
    "admin/contacto/excel.php" => PROJECT_DIR."/modulos/base/controller/admin/contacto/excel.php",
    "admin/mailing/excel.php" => PROJECT_DIR."/modulos/base/controller/admin/mailing/excel.php",
    "registro/verificacion.php" => PROJECT_DIR."/modulos/base/controller/registro/verificacion.php",
    "admin/url-internacional/submit.php" => PROJECT_DIR."/modulos/base/controller/admin/url_internacional/submit.php",
    "admin/core-config/submit.php" => PROJECT_DIR."/modulos/base/controller/admin/core_config/submit.php",
    "admin/smtptest.php" => PROJECT_DIR."/modulos/base/controller/admin/smtp/test.php",
    "manifest.json" => PROJECT_DIR."/modulos/base/controller/manifest.php",
    "service_worker.js" => PROJECT_DIR."/modulos/base/diseno/service_worker.js"
);
?>
