<!DOCTYPE html>
<html lang="<?php echo $lang_root; ?>">
<head>
    <?php if($MyRequest->getPROTOCOLO() == "https://" && $Mobile_detect->isMobile()): ?>
        <link rel="manifest" href="/manifest.json">
        <meta name="theme-color" content="<?=getCoreConfig('base/pwa/theme-color')?>">
        <?php if(getCoreConfig('base/pwa/iconios') != ""): ?>
            <meta name="apple-mobile-web-app-capable" content="yes">
            <meta name="apple-mobile-web-app-status-bar-style" content="black">
            <meta name="apple-mobile-web-app-title" content="<?=getCoreConfig('base/pwa/name')?>">
            <link rel="apple-touch-icon" href="<?=imageResize(getCoreConfig('base/pwa/iconios') ,192,192,true)?>">
            <link rel="apple-touch-icon" sizes="76x76" href="<?=imageResize(getCoreConfig('base/pwa/iconios') ,76,76,true)?>">
            <link rel="apple-touch-icon" sizes="120x120" href="<?=imageResize(getCoreConfig('base/pwa/iconios') ,120,120,true)?>">
            <link rel="apple-touch-icon" sizes="152x152" href="<?=imageResize(getCoreConfig('base/pwa/iconios') ,152,152,true)?>">
        <?php endif; ?>
    <?php endif; ?>
   <?php  include(getVista("admin/layout/widget.headers.phtml")); ?>
</head>



<body class="admin <?php echo $MyRequest->getClassBody($lang_root); ?>" <?php echo (!$MyRequest->isAjax() ? 'style="overflow: hidden;"' : ''); ?>>
 <?php if(!$MyRequest->isAjax()): ?>
<div id="preloaderfullpage" style="position: fixed;top:0;left:0;right:0; bottom:0;background: #f7f7f7;z-index: 100;">
    <div id="loader" style="width: 100px;height: 100px;position: absolute;left:50%; top:50%;background: url('<?php echo getImg('SVG/loader.svg'); ?>') no-repeat center 0; margin:-50px 0 0 -50px;">&nbsp;</div>
</div>
<?php endif; ?>
    <header>
        <div class="w-xxxx-12">
            <div class="w-xxxx-11">
                <?php $logopanel = getImg('logo.png'); ?>

                <?php
                if(getCoreConfig('base/theme/logopanel') != "")
                {
                    if(file_exists(PROJECT_DIR.getCoreConfig('base/theme/logopanel')))
                    {
                        $logopanel = getCoreConfig('base/theme/logopanel');
                    }

                }
                ?>
                <a class="_admin_logo" href="<?php echo $MyRequest->url(MI_CUENTA) ?>"><?php echo makeHTMLImg($logopanel,"","200","200","class='img_logo'"); ?></a>
                
                
                <a target="_blank" class="_btn _txt _my_site" href="/">VER SITIO</a>
            </div>
            <div class="w-xxxx-1 w-xxx-12  w-xx-12  w-x-12">
              
            </div>
        </div>
    </header>
        <main>

        	<div class="w-xxxx-12 page_wrapper">

                    <div class="w-xxxx-12 cont_admin">
                     <?php if($MySession->LoggedIn()): ?>
                        <div class="_btn_collapse_panel"></div>
                        <div class="_left_menu">
                            <ul class="_img_perfil">
                                <li><span class="avatar_mask"><?php echo makeHTMLImg(getAvatar($MySession->GetVar('id'))); ?></span></li>
                                <li><a class="_btn _editar_avatar" href="<?=$MyRequest->url(ADMIN_AVATAR); ?>">Editar</a></li>
                                <?php if($MySession->LoggedIn()): ?>
                                    <li>
                                        <a class="_access _logout" href="/logout.php"><?php echo _("Cerrar sesión"); ?></a>

                                        <form name="lang-admin-frm" action="/admin/lang.php" method="post">
                                        <select name="lang_admin" onchange="$('form[name=lang-admin-frm]').submit();">
                                            <?php if(!empty(getCoreConfig('base/theme/langs-admin'))): ?>
                                            <?php foreach(getCoreConfig('base/theme/langs-admin') as $key_lang): ?>
                                            
                                                <option value="<?=$key_lang?>" <?=($_SESSION["lang_admin"] == $key_lang ? "selected='selected'" : "" )?>><?php echo strtolower($key_lang); ?></option>
                                        
                                            <?php endforeach; ?>
                                            <?php endif; ?>
                                        </select>
                                        </form>
                                    </li>
                                <?php endif; ?>
                              
                            </ul>
                            <ul class="_ul_nav_admin">
                           <?php
                           echo $MyMenuAdmin->getMenu();
                           ?>
                           </ul>
                       </div>
                       <?php endif; ?>
                        <div class="_panel_content">
                            <?php
                                $centro = $MyFrankyMonster->MyPHPFile();
                                $render_phtml = render(str_replace(".php",".phtml",$centro));
                                echo stripJS($render_phtml);
                              
                            ?>
                        </div>

                    </div>

        	</div>
        </main>
        <footer>
            <p><a target="_blank" href="www.cloudstudio.mx">Todos los derechos reservados CloudStudio</a></p>
        </footer>
        <?php echo render("debug.phtml",$MyDebug->Dump()) ?>
        <?php echo render("admin/layout/css.async.phtml"); ?>
        
        <?php echo render("admin/layout/js.phtml",['render_phtml' => $render_phtml,'MyFrankyMonster' => $MyFrankyMonster,'MyConfigure' => $MyConfigure,'Mobile_detect' => $Mobile_detect,'MyMetatag' => $MyMetatag,'lang_root' => $lang_root,"MyRequest" => $MyRequest]); ?>
        <?php echo render("msg.request.phtml"); ?>
</body>
</html>
